# config/packages/security.yaml
security:
    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
    providers:

        in_database:
            entity:
                class: App\Entity\User
                property: username
        
    encoders:
        App\Entity\User:
            algorithm: bcrypt
            cost: 12
            
        Symfony\Component\Security\Core\User\User: bcrypt

    firewalls:
        
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: true

            provider: in_database

            form_login:
                login_path: security_login
                check_path: security_login

            logout:
                path: security_logout
                target: / 

            # http_basic: ~
            
    access_control:
        # require ROLE_ADMIN for /admin*
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/ajout, roles: [ROLE_ADMIN, ROLE_USER] }
        - { path: ^/ajout-champignon, roles: ROLE_USER }
        
