# config/packages/security.yaml
security:
    providers:

        chain_provider:
            chain:
                providers: [in_memory, in_database]

        in_memory:
            memory:
                users:
                    admin:
                        password: $2y$13$Iy4AWy9VRa6xvH0UOIWol.dQ6Btw3fCv.307jX54Iyrg7PRkI7Cfy
                        roles: 'ROLE_ADMIN'

        in_database:
            entity:
                class: App\Entity\User
                property: username

        
    encoders:
        App\Entity\User:
            algorithm: bcrypt
            cost: 12
            
        Symfony\Component\Security\Core\User\User: bcrypt

    firewalls:
        
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: true

            provider: chain_provider

            form_login:
                login_path: security_login
                check_path: security_login

            logout:
                path: security_logout
                target: / 

            # http_basic: ~
            
    access_control:
        # require ROLE_ADMIN for /admin*
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/ajout, roles: ROLE_USER }
        - { path: ^/ajout-champignon, roles: ROLE_USER }
        